// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Only consulted by the Prisma CLI (migrate, studio, ...) — the running
  // app connects through its own adapter in src/lib/prisma.ts using
  // DATABASE_URL (the pooled connection). Migrate needs the *direct*
  // connection because Neon's pooler doesn't support the advisory locks
  // it relies on.
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
