// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Safe by default: the CLI (migrate, studio, ...) targets the Neon
// "development" branch (.env.local) unless PRISMA_TARGET=production is set
// explicitly. This is what stops a stray `prisma migrate dev` or test
// script from touching real production data — see README's "Base de datos
// de desarrollo" section for the full story behind this.
if (process.env.PRISMA_TARGET === "production") {
  config({ path: ".env" });
} else {
  config({ path: ".env.local" });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Only consulted by the Prisma CLI (migrate, studio, ...) — the running
  // app connects through its own adapter in src/lib/prisma.ts using
  // DATABASE_URL (the pooled connection). Migrate needs the *direct*
  // connection because Neon's pooler doesn't support the advisory locks
  // it relies on.
  datasource: {
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
